version: '3'
services:
  website:
    image: crscndo/my-site:latest
    ports:
      - "8080:80"
    container_name: production-site
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

  updater:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Проброс сокета
    command: --interval 30
