apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  index.html: |
    <html>
    <body style="background-color: blue; color: white;">
      <h1>Hacked by Kubernetes ConfigMap!</h1>
      <p>Этот текст загружен не из образа, а из K8s.</p>
    </body>
    </html>
